apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-camc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/asaran-tenant/partner-catalog-4/partner-catalog-camc@sha256:bd6d45587ba1833608689ac4592e686dec5c0f381d033ca7ba3fbde9fd4b9b9a
        name: my-java-springboot
        resources: {}
status: {}
